#[cfg(feature = "dispatch-trace")]
mod enabled {
    use std::collections::BTreeMap;
    use std::fs;
    use std::hint::black_box;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::{Mutex, OnceLock};

    static ROWS: OnceLock<Mutex<BTreeMap<String, Vec<hyperreal::dispatch_trace::DispatchCount>>>> =
        OnceLock::new();
    static TRACE_RUN: AtomicBool = AtomicBool::new(false);

    fn rows() -> &'static Mutex<BTreeMap<String, Vec<hyperreal::dispatch_trace::DispatchCount>>> {
        ROWS.get_or_init(|| Mutex::new(BTreeMap::new()))
    }

    pub fn begin_trace_run() {
        TRACE_RUN.store(true, Ordering::Relaxed);
    }

    pub fn trace_row(name: impl Into<String>, sample: impl FnOnce()) {
        if !TRACE_RUN.load(Ordering::Relaxed) {
            return;
        }

        hyperreal::dispatch_trace::reset();
        hyperreal::dispatch_trace::with_recording(|| {
            sample();
        });
        let counts = hyperreal::dispatch_trace::take();
        if counts.is_empty() {
            return;
        }

        rows()
            .lock()
            .expect("dispatch trace rows lock poisoned")
            .insert(name.into(), counts);
    }

    pub fn trace_cases<T>(name: impl Into<String>, cases: &[T], mut sample: impl FnMut(&T)) {
        trace_row(name, || {
            for case in cases {
                sample(black_box(case));
            }
        });
    }

    pub fn write_report() {
        let rows = rows().lock().expect("dispatch trace rows lock poisoned");
        if rows.is_empty() {
            return;
        }

        let mut out = String::new();
        out.push_str("# Predicated Dispatch Trace\n\n");
        out.push_str("Generated by running `cargo bench --bench predicates --features dispatch-trace,... -- --write-dispatch-trace-md`. Each row is sampled outside Criterion's measured loop. Use a non-tracing benchmark build for timing comparisons; the trace feature intentionally compiles diagnostic hooks into predicated, realistic_blas, and hyperreal.\n\n");
        out.push_str("| Benchmark Row | Layer | Operation | Path | Count |\n");
        out.push_str("| --- | --- | --- | --- | ---: |\n");
        for (row, counts) in rows.iter() {
            for count in counts {
                out.push_str(&format!(
                    "| `{}` | `{}` | `{}` | `{}` | {} |\n",
                    row, count.layer, count.operation, count.path, count.count
                ));
            }
        }

        if let Err(error) = fs::write("dispatch_trace.md", out) {
            eprintln!("failed to update dispatch_trace.md: {error}");
        }
    }
}

#[cfg(not(feature = "dispatch-trace"))]
mod enabled {
    pub fn begin_trace_run() {}

    #[cfg(feature = "parallel")]
    pub fn trace_row(name: impl Into<String>, sample: impl FnOnce()) {
        let _ = name;
        let _ = sample;
    }

    pub fn trace_cases<T>(name: impl Into<String>, cases: &[T], sample: impl FnMut(&T)) {
        let _ = name;
        let _ = cases;
        let _ = sample;
    }

    pub fn write_report() {}
}

pub(crate) use enabled::trace_cases as trace_dispatch_cases;
#[cfg(feature = "parallel")]
pub(crate) use enabled::trace_row as trace_dispatch_row;

pub(crate) fn begin_dispatch_trace_run() {
    enabled::begin_trace_run();
}

pub(crate) fn write_dispatch_trace_report() {
    enabled::write_report();
}
