#![allow(dead_code, unused_imports)]

#[cfg(feature = "dispatch-trace")]
mod enabled {
    use std::collections::BTreeMap;
    use std::fs;
    use std::hint::black_box;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::{Mutex, OnceLock};

    static ROWS: OnceLock<Mutex<BTreeMap<String, hyperreal::dispatch_trace::TraceSnapshot>>> =
        OnceLock::new();
    static TRACE_RUN: AtomicBool = AtomicBool::new(false);

    fn rows() -> &'static Mutex<BTreeMap<String, hyperreal::dispatch_trace::TraceSnapshot>> {
        ROWS.get_or_init(|| Mutex::new(BTreeMap::new()))
    }

    pub fn begin_trace_run() {
        TRACE_RUN.store(true, Ordering::Relaxed);
    }

    pub fn trace_row(name: impl Into<String>, sample: impl FnOnce()) {
        if !TRACE_RUN.load(Ordering::Relaxed) {
            return;
        }

        hyperreal::dispatch_trace::reset();
        hyperreal::dispatch_trace::with_recording(|| {
            sample();
        });
        let trace = hyperreal::dispatch_trace::take_trace();
        if trace.dispatch.is_empty() {
            return;
        }

        rows()
            .lock()
            .expect("dispatch trace rows lock poisoned")
            .insert(name.into(), trace);
    }

    pub fn trace_cases<T>(name: impl Into<String>, cases: &[T], mut sample: impl FnMut(&T)) {
        trace_row(name, || {
            for case in cases {
                sample(black_box(case));
            }
        });
    }

    pub fn write_report() {
        let rows = rows().lock().expect("dispatch trace rows lock poisoned");
        if rows.is_empty() {
            return;
        }

        let mut out = String::new();
        out.push_str("# Hyperlimit Dispatch Trace\n\n");
        out.push_str("Generated by running `cargo bench --bench predicates --features dispatch-trace -- --write-dispatch-trace-md`. Each row is sampled outside Criterion's measured loop. Use a non-tracing benchmark build for timing comparisons; the trace feature intentionally compiles diagnostic hooks into hyperlimit and hyperreal.\n\n");
        out.push_str("## Correlation Summary\n\n");
        out.push_str("| Benchmark Row | Dispatch | Predicate | Linear Algebra | Object Facts | Scalar Facts | Detailed Facts | Unknown Facts | Rational Kinds | Sign/Zero Queries | Exact Reducers | Approximation | Approx Starts | Approx Cache | Refinement | Predicate Stages | Cache | Fallback/Abort | Rational Temps | Rational Reductions | Rational GCDs |\n");
        out.push_str("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n");
        for (row, trace) in rows.iter() {
            let summary = trace.correlation_summary();
            out.push_str(&format!(
                "| `{}` | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
                row,
                summary.dispatch_events,
                summary.predicate_events,
                summary.linear_algebra_events,
                summary.object_fact_events,
                summary.scalar_fact_events,
                summary.detailed_fact_events,
                summary.unknown_fact_events,
                summary.exact_rational_kind_events,
                summary.sign_or_zero_query_events,
                summary.exact_reducer_events,
                summary.approximation_events,
                summary.approximation_start_events,
                summary.approximation_cache_events,
                summary.refinement_events,
                summary.predicate_decision_stage_events,
                summary.cache_events,
                summary.fallback_or_abort_events,
                summary.rational_temporaries,
                summary.rational_reductions,
                summary.rational_gcds
            ));
        }
        out.push('\n');
        out.push_str("## Dispatch Paths\n\n");
        out.push_str("| Benchmark Row | Layer | Operation | Path | Count |\n");
        out.push_str("| --- | --- | --- | --- | ---: |\n");
        for (row, trace) in rows.iter() {
            for count in &trace.dispatch {
                out.push_str(&format!(
                    "| `{}` | `{}` | `{}` | `{}` | {} |\n",
                    row, count.layer, count.operation, count.path, count.count
                ));
            }
        }
        out.push_str("\n## Operation Summary\n\n");
        out.push_str("| Benchmark Row | Layer | Operation | Count |\n");
        out.push_str("| --- | --- | --- | ---: |\n");
        for (row, trace) in rows.iter() {
            for summary in trace.operation_summaries() {
                out.push_str(&format!(
                    "| `{}` | `{}` | `{}` | {} |\n",
                    row, summary.layer, summary.operation, summary.count
                ));
            }
        }
        out.push_str("\n## Rational Reducer Summary\n\n");
        out.push_str("| Benchmark Row | Temporaries | Reductions | GCDs | Peak Operand Bits |\n");
        out.push_str("| --- | ---: | ---: | ---: | ---: |\n");
        for (row, trace) in rows.iter() {
            out.push_str(&format!(
                "| `{}` | {} | {} | {} | {} |\n",
                row,
                trace.rational.temporary_rationals,
                trace.rational.reductions,
                trace.rational.gcds,
                trace.rational.peak_operand_bits
            ));
        }

        if let Err(error) = fs::write("dispatch_trace.md", out) {
            eprintln!("failed to update dispatch_trace.md: {error}");
        }
    }
}

#[cfg(not(feature = "dispatch-trace"))]
mod enabled {
    pub fn begin_trace_run() {}

    #[cfg(feature = "parallel")]
    pub fn trace_row(name: impl Into<String>, sample: impl FnOnce()) {
        let _ = name;
        let _ = sample;
    }

    pub fn trace_cases<T>(name: impl Into<String>, cases: &[T], sample: impl FnMut(&T)) {
        let _ = name;
        let _ = cases;
        let _ = sample;
    }

    pub fn write_report() {}
}

pub(crate) use enabled::trace_cases as trace_dispatch_cases;
#[cfg(feature = "parallel")]
pub(crate) use enabled::trace_row as trace_dispatch_row;

pub(crate) fn begin_dispatch_trace_run() {
    enabled::begin_trace_run();
}

pub(crate) fn write_dispatch_trace_report() {
    enabled::write_report();
}
